### PR TITLE
Fixing port on ldap issue

### PR DESCRIPTION
**Pull request by AlexLarentis01**
Hello FreePBX devs,
hope ur all doing great. I noticed that changing the port is not possible, because the name of the label in the frontend is wrong. I am able to change it if I manually rename the label from `openldap2-post` to `openldap2-port` it works. is a huge pita though because on every save it defaults back to 389.

### CODE REVIEW

**Comment by AlexLarentis01** [comment]
Is there any other file witch requires changes?

**Comment by kapilgupta01** [comment]
Hi @AlexLarentis01 Thank you for your contribution, however it looks like you have not yet filled the CLA. Could you please signed the CLA for us to accept your fixes.

Thank you for using FreePBX
Kapil

**Comment by kapilgupta01** [comment]
Hi @AlexLarentis01 

Thank you for your contribution, however it looks like you have not yet filled the CLA., Could you please follow the below link to signed the CLA for us to accept your fixes.

https://oss-cla.sangoma.com/freepbx/userman

Thank you for using FreePBX
Kapil Gupta

**Comment by kapilgupta01** [comment]
Hi @AlexLarentis01 Thanks for your contribution, however without CLA signing we can not accept your PR. 

Also, this respective error which you are trying to fix in 14 already taken care in 16 and 17 release. 

Thank you for using FreePBX
Kapil

**Pull request closed without merging**
